name: Rebuild static site

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"  # every 3 hours (UTC)

permissions:
  contents: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build static site
        run: python build_static.py

      - name: Commit and push updates
        id: push_changes
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/ data/ earnings/ static/ templates/ app.py build_static.py
          if git diff --cached --quiet; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          git commit -m "Automated static rebuild"
          git push
          echo "changed=true" >> "$GITHUB_OUTPUT"

      - name: Trigger deploy workflow
        if: steps.push_changes.outputs.changed == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "deploy.yml",
              ref: "main"
            })
