name: Rebuild static site

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */5 * * *"  # every 5 hours (UTC)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build static site
        run: python build_static.py

      - name: Commit and push updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/ data/ earnings/ static/ templates/ app.py build_static.py
          git commit -m "Automated static rebuild" || exit 0
          git push
